"""Add Full-Service mode and sequence tracking

Revision ID: 9151eeb6401d
Revises: a53d3d7ebb5e
Create Date: 2025-11-11 12:19:52.153708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9151eeb6401d'
down_revision = 'a53d3d7ebb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sequence_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_mailer_id_used', sa.String(length=20), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mail_service_mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('mail_service_mode')
        batch_op.drop_column('sequence_end')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('last_mailer_id_used')
        batch_op.drop_column('last_sequence_number')

    # ### end Alembic commands ###
