"""Add company settings to customers

Revision ID: a53d3d7ebb5e
Revises: e9e6903c6b7e
Create Date: 2025-11-11 08:48:27.559152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53d3d7ebb5e'
down_revision = 'e9e6903c6b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_mailer_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('default_service_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('default_barcode_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('default_sequence_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('api_provider', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('api_provider')
        batch_op.drop_column('default_sequence_start')
        batch_op.drop_column('default_barcode_id')
        batch_op.drop_column('default_service_type')
        batch_op.drop_column('default_mailer_id')

    # ### end Alembic commands ###
